# Generated by Django 3.2.8 on 2021-10-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_appointment_departments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['id'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
