
GENERAL_HEALTH = 'General Health'
CARDIOLOGY = 'Cardiology'
DENTAL = 'Dental'
NEUROLOGY = 'Neurology'
ORTHOPAEDICS = 'Orthopaedics'

DEPARTMENTS = (
    # (ALL_CATEGORIES, ALL_CATEGORIES),
    (GENERAL_HEALTH, GENERAL_HEALTH),
    (CARDIOLOGY, CARDIOLOGY),
    (DENTAL, DENTAL),
    (NEUROLOGY, NEUROLOGY),
    (ORTHOPAEDICS, ORTHOPAEDICS)
)
